
images:
  browser:
    label_match: wr.name
    label_prefix: wr.
    image_prefix: oldwebtoday/
    exclude_labels:
      - icon

view:
  image_prefix: oldwebtoday/
  view_template: '${VIEW_TEMPLATE}'
  home_template: '${HOME_TEMPLATE}'
  controls_template: '${CONTROLS_TEMPLATE}'
  override: browser
  default_flock: browsers


